# Generated by Django 3.1.3 on 2020-11-17 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='editor',
            field=models.TextField(blank=True),
        ),
    ]
